@echo off
cd %~dp0
echo FAUST Backend ASR Service Starting...
echo Activating conda environment 'my-neuro'...
conda activate my-neuro && python asr_api.py >log_asr.log 2>&1
echo Running ASR service...