import faust_backend.config_loader as conf
EMBED_MODEL = conf.EMBED_MODEL
EMBED_DIM = 1536
MAX_CHUNK_CHARS = 3000
CHUNK_OVERLAP_CHARS = 300
MIN_SCORE_PATCH = -0.15
MAX_SCORE_PATCH = 0.15
ENTITY_DEDUP_THRESHOLD = 0.85
